version: '3'
services:
  mysql_primary:
    image: mysql:5.7
    env_file:
      - ./primary/mysql_primary.env
    container_name: "mysql_primary"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./primary/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./primary/data:/var/lib/mysql
    networks:
      - overlay

  mysql_replica:
    image: mysql:5.7
    env_file:
      - ./replica/mysql_replica.env
    container_name: "mysql_replica"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_primary
    volumes:
      - ./replica/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./replica/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:

